USE DBRENDAFIXA
GO

	CREATE TABLE IMPOSTO (
		ID_IMPOSTO SMALLINT NOT NULL,
		TX_NOME VARCHAR(8) NOT NULL,
		TX_DESCRICAO VARCHAR(50) NOT NULL,
		TX_USUARIOCRIACAO VARCHAR(25) NOT NULL,
		DT_CRIACAO DATETIME2(3) CONSTRAINT DF_IMPOSTO_DT_CRIACAO DEFAULT GETDATE() NOT NULL,
		TX_USUARIOATUALIZACAO VARCHAR(25) NULL,
		DT_ATUALIZACAO DATETIME2(3) NULL,
		CONSTRAINT PK_IMPOSTO PRIMARY KEY (ID_IMPOSTO)
	);
	------------------------------------------------------------------------------------------------------------------------
	CREATE TABLE CONFIGURACAOIMPOSTO (
		ID_IMPOSTO SMALLINT NOT NULL,
		ID_CONFIGURACAOIMPOSTO TINYINT NOT NULL,
		TX_RENDIMENTO DECIMAL(12, 8) NOT NULL,
		NM_DIASUTEIS SMALLINT NOT NULL,
		TX_USUARIOCRIACAO VARCHAR(25) NOT NULL,
		DT_CRIACAO DATETIME2(3) CONSTRAINT DF_CONFIGURACAOIMPOSTO_DT_CRIACAO DEFAULT GETDATE() NOT NULL,
		TX_USUARIOATUALIZACAO VARCHAR(25) NULL,
		DT_ATUALIZACAO DATETIME2(3) NULL,
		CONSTRAINT PK_CONFIGURACAOIMPOSTO PRIMARY KEY (ID_IMPOSTO, ID_CONFIGURACAOIMPOSTO)
	);

	ALTER TABLE CONFIGURACAOIMPOSTO ADD CONSTRAINT FK_CONFIGURACAOIMPOSTO_IMPOSTO
	FOREIGN KEY (ID_IMPOSTO) REFERENCES IMPOSTO(ID_IMPOSTO);