USE DBRENDAFIXA
GO

CREATE TABLE INDEXADOR (
		ID_INDEXADOR TINYINT NOT NULL,
		TX_NOME VARCHAR(20) NOT NULL, 
		TX_DESCRICAO VARCHAR(255) NULL,
		NM_RENDIMENTO DECIMAL(12, 8) NOT NULL,
		TX_USUARIOCRIACAO VARCHAR(25) NOT NULL,
		DT_CRIACAO DATETIME2(3) CONSTRAINT DF_INDEXADOR_DT_CRIACAO DEFAULT GETDATE() NOT NULL,
		TX_USUARIOATUALIZACAO VARCHAR(25) NULL,
		DT_ATUALIZACAO DATETIME2(3) NULL,
		CONSTRAINT PK_INDEXADOR PRIMARY KEY (ID_INDEXADOR)
	);