USE DBRENDAFIXA
GO

	CREATE TABLE [INVESTIMENTO] (
		ID_INVESTIMENTO UNIQUEIDENTIFIER NOT NULL,
		ID_INVESTIDOR UNIQUEIDENTIFIER NOT NULL,
		TX_DOCUMENTOFEDERAL VARCHAR(14) NOT NULL,
		NM_VALORINICIAL DECIMAL(20, 4) NOT NULL,
		NM_VALORFINAL DECIMAL(20, 4) NOT NULL,
		NM_VALORIMPOSTO DECIMAL(20, 8) NOT NULL,
		NM_TAXARENDIMENTO DECIMAL(12, 8) CONSTRAINT DF_INVESTIMENTO_NM_TAXARENDIMENTO DEFAULT 100 NOT NULL,
		NM_TAXAADICIONAL DECIMAL(12, 8) CONSTRAINT DF_INVESTIMENTO_NM_TAXAADICIONAL DEFAULT 0 NOT NULL,
		DT_INICIAL DATE NOT NULL,
		DT_FINAL DATE NOT NULL,
		ID_INDEXADOR TINYINT NOT NULL,
		BO_LIQUIDADO BIT CONSTRAINT DF_INVESTIMENTO_BO_LIQUIDADO DEFAULT 0 NOT NULL,
		BO_ISENTOIMPOSTO BIT CONSTRAINT DF_INVESTIMENTO_BO_ISENTOIMPOSTO DEFAULT 0 NOT NULL,
		TX_USUARIO VARCHAR(25) NOT NULL,
		DT_CRIACAO DATETIME2(3) CONSTRAINT DF_INVESTIMENTO_DT_CRIACAO DEFAULT GETDATE() NOT NULL,
		TX_USUARIOATUALIZACAO VARCHAR(25) NULL,
		DT_ATUALIZACAO DATETIME2(3) NULL,
		CONSTRAINT PK_INVESTIMENTO PRIMARY KEY(ID_INVESTIMENTO)
	);

	ALTER TABLE INVESTIMENTO ADD CONSTRAINT UQ_INVESTIMENTO_INVESTIDOR
	UNIQUE(ID_INVESTIMENTO, ID_INVESTIDOR, TX_DOCUMENTOFEDERAL);

	ALTER TABLE INVESTIMENTO ADD CONSTRAINT FK_INVESTIMENTO_INDEXADOR
	FOREIGN KEY(ID_INDEXADOR) REFERENCES INDEXADOR(ID_INDEXADOR);
	------------------------------------------------------------------------------------------------------------------------
	CREATE TABLE [MOVIMENTACAO] (
		ID_INVESTIMENTO UNIQUEIDENTIFIER NOT NULL,
		ID_MOVIMENTACAO SMALLINT NOT NULL,
		DT_MOVIMENTACAO DATE NOT NULL,
		NM_VALORBRUTOTOTAL DECIMAL(20, 4) NOT NULL,
		NM_VALORLIQUIDOTOTAL DECIMAL(20, 4) NOT NULL,
		NM_VALORBRUTO DECIMAL(12, 4) NOT NULL,
		NM_VALORLIQUIDO DECIMAL(12, 4) NOT NULL,
		TX_USUARIO VARCHAR(25) NOT NULL,
		DT_CRIACAO DATETIME2(3) CONSTRAINT DF_MOVIMENTACAO_DT_CRIACAO DEFAULT GETDATE() NOT NULL,
		TX_USUARIOATUALIZACAO VARCHAR(25) NULL,
		DT_ATUALIZACAO DATETIME2(3) NULL,
		CONSTRAINT PK_MOVIMENTACAO PRIMARY KEY(ID_INVESTIMENTO, ID_MOVIMENTACAO)
	);

	ALTER TABLE MOVIMENTACAO ADD CONSTRAINT FK_MOVIMENTACAO_INVESTIMENTO 
	FOREIGN KEY (ID_INVESTIMENTO) REFERENCES INVESTIMENTO(ID_INVESTIMENTO);
	------------------------------------------------------------------------------------------------------------------------
	CREATE TABLE MOVIMENTACAOIMPOSTO (
		ID_INVESTIMENTO UNIQUEIDENTIFIER NOT NULL,
		ID_MOVIMENTACAO SMALLINT NOT NULL,
		ID_IMPOSTO TINYINT NOT NULL,
		NM_VALORIMPOSTO DECIMAL(20, 8) CONSTRAINT DF_MOVIMENTACAOIMPOSTO_NM_VALORIMPOSTO DEFAULT 0 NOT NULL,
		CONSTRAINT PK_MOVIMENTACAOIMPOSTO PRIMARY KEY(ID_INVESTIMENTO, ID_MOVIMENTACAO, ID_IMPOSTO)
	);

	ALTER TABLE MOVIMENTACAOIMPOSTO ADD CONSTRAINT FK_MOVIMENTACAOIMPOSTO_MOVIMENTACAO 
	FOREIGN KEY (ID_INVESTIMENTO, ID_MOVIMENTACAO) REFERENCES MOVIMENTACAO(ID_INVESTIMENTO, ID_MOVIMENTACAO);
	
	ALTER TABLE MOVIMENTACAOIMPOSTO ADD CONSTRAINT FK_MOVIMENTACAOIMPOSTO_IMPOSTO 
	FOREIGN KEY (ID_IMPOSTO) REFERENCES IMPOSTO(ID_IMPOSTO);
	------------------------------------------------------------------------------------------------------------------------
	CREATE TABLE RESGATE(
		ID_INVESTIMENTO UNIQUEIDENTIFIER NOT NULL,
		ID_RESGATE SMALLINT NOT NULL,
		ID_INVESTIDOR UNIQUEIDENTIFIER NOT NULL,
		ID_PRODUTO UNIQUEIDENTIFIER NOT NULL,
		NM_VALOR DECIMAL(20, 4) NOT NULL,
		NM_IMPOSTO DECIMAL(20, 8) NOT NULL,
		DT_RESGATE DATE NOT NULL,
		TX_USUARIO VARCHAR(25) NOT NULL,
		DT_CRIACAO DATETIME2(3) CONSTRAINT DF_RESGATE_DT_CRIACAO DEFAULT GETDATE() NOT NULL,
		TX_USUARIO_ATUALIZACAO VARCHAR(25) NULL,
		DT_ATUALIZACAO DATETIME2(3) NULL,
		CONSTRAINT PK_RESGATE PRIMARY KEY(ID_INVESTIMENTO, ID_RESGATE)
	);

	ALTER TABLE RESGATE ADD CONSTRAINT FK_RESGATE_INVESTIMENTO
	FOREIGN KEY (ID_INVESTIMENTO) REFERENCES INVESTIMENTO(ID_INVESTIMENTO);
