USE DBRENDAFIXA
GO

	IF OBJECT_ID (N'dbo.RESGATE', N'U') IS NOT NULL
		DROP TABLE RESGATE

	IF OBJECT_ID (N'dbo.MOVIMENTACAOIMPOSTO', N'U') IS NOT NULL
		DROP TABLE MOVIMENTACAOIMPOSTO

	IF OBJECT_ID (N'dbo.MOVIMENTACAO', N'U') IS NOT NULL
		DROP TABLE MOVIMENTACAO

	IF OBJECT_ID (N'dbo.INVESTIMENTO', N'U') IS NOT NULL
		DROP TABLE INVESTIMENTO